### ISSUE TITLE
Can't find the .app?

### ISSUE THREAD

**Issue by sbilde** [itd/OpenInSublimeText#2]
Hi there.

I'm really interested in installing your application. I can't seem to locate the .app, which I shall drag to the toolbar?

Am I missing something?

/Steffen

**Comment by itd** [comment]
Try this:

got to: https://github.com/itd/OpenInSublimeText/downloads   and click the "download as a zip" button.

Then, once it's downloaded, rename the folder: OpenInSublimeText.app
That'll turn the archive into an "application". Then, I usually put the app somewhere like the Applications folder. 

Last step. Drag the app onto the top of a finder window. I did a little video for another widget to show you how here: : http://www.youtube.com/watch?v=1mkDYW2nsCc

Let me know if it works or not. I'm glad to help.

**Comment by sbilde** [comment]
That worked just perfect!..- Thanks a lot, and what a great little app :)
